# fly.toml app configuration file generated for ffff-1718874154-server on 2024-06-20T09:03:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ffff-1718874154-server'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
